sudo: false
language: node_js
node_js:
  - '10.15.1'
cache:
  directories:
    - node_modules

branches:
  only:
    - master
install:
  - npm install
script:
  - npm test
after_success:
  - npm run coverage
